apiVersion: v1
kind: DeploymentConfig
metadata:
  generateName: my-perfect-node-app-
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deploymentconfig: my-perfect-node-app-2020
    spec:
      containers:
        - image: my-perfect-node-app
          name: my-perfect-node-app
          ports:
            - containerPort: 8080
              protocol: "TCP"
          command: ["/bin/sh", "-c", "while true ; do date; sleep 1; done;"]
  # triggers:
  # - type: ConfigChange
